-- ============================================================================
--  rehat-durasi-server-v83.sql  —  JANGKAR JAM SERVER UNTUK SKOR
--
--  BERDIRI SENDIRI: tidak perlu menjalankan v80/v82 terlebih dulu.
--  Memperbaiki error "relation public.rehat_nonce does not exist" — bagian 0-2
--  kini menciptakan sendiri tabel/kolom yang dibutuhkan bila belum ada.
--  Aman dijalankan berulang kali (create ... if not exists / or replace).
--
--  Celah yang ditutup v83:
--   Selama ini DURASI RONDE dilaporkan klien sendiri lewat p_waktu, padahal
--   plafon arcade dan poin puzzle dihitung darinya. Lewat satu panggilan
--   curl memakai anon key (yang memang terlihat di kode — itu wajar), siapa
--   pun bisa mengaku bermain 2 jam (plafon ngopi jadi ~93.612) atau menyelesaikan
--   puzzle sekejap (poin nyaris maksimal) tanpa benar-benar bermain.
--
--  Cara v83 menutupnya:
--   1) RPC baru rehat_mulai_ronde(): klien mendaftarkan nonce SAAT RONDE
--      DIMULAI, jadi server memegang jam mulai yang tidak bisa dipalsukan.
--   2) rehat_kirim_skor() menjangkar durasi ke jam server:
--        - arcade : waktu plafon = min(p_waktu, durasi_server + 15 dtk)
--                   -> mengaku bermain lebih lama tidak menaikkan plafon;
--                      jeda/pindah tab tidak pernah merugikan (min).
--        - puzzle : waktu poin   = max(p_waktu, durasi_server - 180 dtk)
--                   -> taktik "jeda berjam-jam lalu mengaku 30 detik" kandas;
--                      jeda singkat sampai 3 menit tetap dimaafkan.
--   3) Rem laju 30 kiriman/10 menit per nama kini dihitung dari SAAT SKOR
--      DIKIRIM (kolom dipakai_at), bukan dari saat ronde mulai.
--   4) Klien lama (nonce baru dibuat saat kirim) TETAP DITERIMA dengan
--      perilaku lama — tidak ada pemain yang patah aplikasinya.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Tabel skor dasar (setara v71-v80; dilewati otomatis bila sudah ada)
-- ---------------------------------------------------------------------------
create table if not exists public.rehat_skor (
  id          bigint generated by default as identity primary key,
  game        text        not null,
  nama        text        not null,
  skor        integer     not null default 0,
  created_at  timestamptz not null default now()
);

alter table public.rehat_skor add column if not exists level   text not null default '';
alter table public.rehat_skor add column if not exists waktu   integer;   -- bukti audit
alter table public.rehat_skor add column if not exists langkah integer;   -- bukti audit

alter table public.rehat_skor drop constraint if exists rehat_skor_game_check;
alter table public.rehat_skor add constraint rehat_skor_game_check
  check (game in ('flyer','ngopi','puzzle'));

create index if not exists rehat_skor_game_skor_idx
  on public.rehat_skor (game, skor desc);

-- rapikan duplikat lama (simpan skor tertinggi per game+nama+level), lalu
-- pasang kunci unik. Index lama v75 tanpa kolom level dibuang dulu supaya
-- satu nama boleh punya baris berbeda untuk tiap tingkat puzzle.
delete from public.rehat_skor a using public.rehat_skor b
 where a.game=b.game and lower(btrim(a.nama))=lower(btrim(b.nama)) and a.level=b.level
   and (b.skor>a.skor or (b.skor=a.skor and b.created_at<a.created_at))
   and a.id<>b.id;

drop index if exists public.rehat_skor_unik;
create unique index rehat_skor_unik
  on public.rehat_skor (game, lower(btrim(nama)), level);

-- ---------------------------------------------------------------------------
-- 1. CABUT JALUR TULIS PUBLIK (inti pengamanan v80) + pensiunkan trigger lama
-- ---------------------------------------------------------------------------
alter table public.rehat_skor enable row level security;

drop policy if exists rehat_tulis_publik on public.rehat_skor;
drop policy if exists rehat_ubah_publik  on public.rehat_skor;
drop policy if exists rehat_hapus_publik on public.rehat_skor;

-- trigger penjaga v75 tidak mengenal kolom level dan bisa menelan skor puzzle
-- beda tingkat; tugasnya sudah digantikan RPC di bawah
drop trigger if exists rehat_skor_guard on public.rehat_skor;
drop function if exists public.rehat_skor_guard();

revoke insert, update, delete, truncate on public.rehat_skor from anon;
revoke insert, update, delete, truncate on public.rehat_skor from authenticated;

-- baca tetap terbuka supaya papan peringkat bisa tampil tanpa login
drop policy if exists rehat_baca_publik on public.rehat_skor;
create policy rehat_baca_publik on public.rehat_skor for select using (true);
grant select on public.rehat_skor to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. Buku nonce: satu ronde = satu kiriman (anti replay) + jam mulai server
-- ---------------------------------------------------------------------------
create table if not exists public.rehat_nonce (
  nonce      text primary key,
  game       text,
  nama       text,
  created_at timestamptz not null default now()
);
create index if not exists rehat_nonce_nama_idx
  on public.rehat_nonce (nama, created_at desc);

alter table public.rehat_nonce enable row level security;
-- tanpa policy apa pun: anon sama sekali tidak bisa membaca/menulis tabel ini
revoke all on public.rehat_nonce from anon;
revoke all on public.rehat_nonce from authenticated;

-- kolom penanda: sudah dipakai kirim + kapan.
-- Baris lama semuanya nonce yang dibuat saat kirim -> dipakai = true.
alter table public.rehat_nonce add column if not exists dipakai    boolean not null default true;
alter table public.rehat_nonce add column if not exists dipakai_at timestamptz;
update public.rehat_nonce set dipakai_at = created_at where dipakai and dipakai_at is null;

-- ---------------------------------------------------------------------------
-- 3. PENDAFTARAN JAM MULAI RONDE (dipanggil klien v83 ke atas)
-- ---------------------------------------------------------------------------
create or replace function public.rehat_mulai_ronde(
  p_game  text,
  p_nonce text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_baru integer;
begin
  if p_game is null or p_game not in ('flyer','ngopi','puzzle') then return; end if;
  if p_nonce is null or char_length(p_nonce) < 8 or char_length(p_nonce) > 64 then return; end if;

  -- rem darurat anti banjir pendaftaran (jauh di atas pemakaian wajar acara)
  select count(*) into v_baru
    from public.rehat_nonce
   where created_at > now() - interval '1 hour';
  if v_baru > 50000 then return; end if;

  begin
    insert into public.rehat_nonce(nonce, game, nama, dipakai)
    values (p_nonce, p_game, '', false);
  exception when unique_violation then
    return;  -- nonce sudah terdaftar: abaikan saja
  end;

  -- sapu bersih catatan lama sesekali agar tabel tetap ringan
  if random() < 0.02 then
    delete from public.rehat_nonce where created_at < now() - interval '3 days';
  end if;
end;
$$;

revoke all on function public.rehat_mulai_ronde(text,text) from public;
grant execute on function public.rehat_mulai_ronde(text,text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. SATU-SATUNYA PINTU MASUK SKOR (v83: durasi dijangkar jam server)
-- ---------------------------------------------------------------------------
create or replace function public.rehat_kirim_skor(
  p_game    text,
  p_nama    text,
  p_skor    integer,
  p_level   text    default '',
  p_waktu   integer default null,
  p_langkah integer default null,
  p_nonce   text    default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nama   text;
  v_level  text;
  v_skor   integer;
  v_basis  integer;
  v_plafon integer;
  v_minlangkah integer;
  v_minwaktu   integer;
  v_lama   integer;
  v_banyak integer;
  v_mulai  timestamptz;
  v_dur    integer;
  v_waktu  integer;
begin
  -- ---------- nama ----------
  v_nama := btrim(coalesce(p_nama, ''));
  if char_length(v_nama) < 1 or char_length(v_nama) > 24 then
    return null;
  end if;

  -- ---------- game ----------
  if p_game is null or p_game not in ('flyer','ngopi','puzzle') then
    return null;
  end if;

  -- ---------- level ----------
  v_level := coalesce(p_level, '');
  if p_game = 'puzzle' then
    if v_level not in ('3x3','4x4','5x5') then return null; end if;
  else
    v_level := '';
  end if;

  -- ---------- durasi wajib & wajar ----------
  if p_waktu is null or p_waktu < 1 or p_waktu > 7200 then
    return null;
  end if;
  if p_langkah is not null and (p_langkah < 0 or p_langkah > 20000) then
    return null;
  end if;

  -- ---------- nonce wajib ----------
  if p_nonce is null or char_length(p_nonce) < 8 or char_length(p_nonce) > 64 then
    return null;
  end if;

  -- ---------- rem laju per nama (dihitung dari SAAT KIRIM, v83) ----------
  select count(*) into v_banyak
    from public.rehat_nonce
   where nama = lower(v_nama)
     and coalesce(dipakai_at, created_at) > now() - interval '10 minutes';
  if v_banyak >= 30 then
    return null;
  end if;

  -- ---------- nonce sekali-pakai + jangkar jam server (v83) ----------
  -- Nonce yang didaftarkan lewat rehat_mulai_ronde() saat ronde DIMULAI membawa
  -- jam mulai versi server; dikunci di sini supaya tidak bisa dipakai dua kali.
  -- Nonce tak dikenal = klien lama: dicatat sekarang dan durasi tetap memakai
  -- laporan klien seperti sediakala.
  update public.rehat_nonce
     set dipakai = true, nama = lower(v_nama), dipakai_at = now()
   where nonce = p_nonce
     and dipakai = false
   returning created_at into v_mulai;
  if not found then
    begin
      insert into public.rehat_nonce(nonce, game, nama, dipakai, dipakai_at)
      values (p_nonce, p_game, lower(v_nama), true, now());
      v_mulai := null;
    exception when unique_violation then
      return null;   -- ronde ini sudah pernah dikirim (anti replay)
    end;
  end if;

  -- sapu bersih catatan nonce lama sesekali agar tabel tetap ringan
  if random() < 0.02 then
    delete from public.rehat_nonce where created_at < now() - interval '3 days';
  end if;

  -- durasi versi jam server (null untuk klien lama)
  if v_mulai is not null then
    v_dur := greatest(1, floor(extract(epoch from (now() - v_mulai)))::int);
  else
    v_dur := null;
  end if;

  -- =========================================================================
  -- HITUNG ULANG / BATASI SKOR DI SERVER — angka dari klien tidak dipercaya
  -- =========================================================================
  if p_game = 'puzzle' then
    if p_langkah is null then return null; end if;

    v_basis      := case v_level when '3x3' then 3000 when '5x5' then 9500 else 6000 end;
    -- p_langkah bersatuan berbobot (tukar*2 + putar); ambang minimum yang tepat
    -- sudah diperiksa sisi pemain lewat minAksi() (jarak siklus + sisa putaran).
    v_minlangkah := case v_level when '3x3' then 6    when '5x5' then 16   else 10   end;
    v_minwaktu   := case v_level when '3x3' then 3    when '5x5' then 12   else 6    end;

    -- mustahil menyusun dengan langkah/waktu di bawah batas ini
    if p_langkah < v_minlangkah then return null; end if;
    if p_waktu   < v_minwaktu   then return null; end if;
    -- batas kecepatan ketukan manusia — tetap dari jam klien (jeda tak dihitung)
    if p_langkah > (p_waktu + 1) * 25 then return null; end if;

    -- v83: waktu poin dijangkar jam server. Mengaku lebih cepat tidak lagi
    -- menaikkan poin; jeda sampai 3 menit tetap dimaafkan.
    if v_dur is not null then
      v_waktu := greatest(p_waktu, v_dur - 180);
    else
      v_waktu := p_waktu;
    end if;

    -- rumus resmi puzzle, dihitung di server (langkah berbobot: tukar*2+putar)
    v_skor := greatest(10, least(v_basis, v_basis - v_waktu * 30 - p_langkah * 4));

  else
    -- arcade: plafon laju terhadap durasi. v83 membatasi durasi laporan klien
    -- dengan durasi jam server (+15 dtk tenggang kirim). Yang dipakai selalu
    -- yang TERKECIL, jadi jeda/pindah tab tidak pernah merugikan pemain.
    --   flyer : 1 pipa butuh >= ~0,8 detik  -> plafon 1,3 poin/detik
    --   ngopi : item terbaik 5 poin per ~0,4 detik -> plafon 13 poin/detik
    if v_dur is not null then
      v_waktu := least(p_waktu, v_dur + 15);
    else
      v_waktu := p_waktu;
    end if;
    v_plafon := case p_game
                  when 'flyer' then 3  + ceil(v_waktu * 1.3)::int
                  else              12 + ceil(v_waktu * 13)::int
                end;
    v_skor := least(greatest(coalesce(p_skor, 0), 0), v_plafon);
  end if;

  if v_skor <= 0 or v_skor > 100000 then
    return null;
  end if;

  -- =========================================================================
  -- UPSERT: satu baris per (game, nama, level), hanya diganti bila lebih tinggi
  -- =========================================================================
  select skor into v_lama
    from public.rehat_skor
   where game = p_game
     and lower(btrim(nama)) = lower(v_nama)
     and level = v_level
   limit 1;

  if v_lama is null then
    begin
      insert into public.rehat_skor(game, nama, skor, level, waktu, langkah)
      values (p_game, v_nama, v_skor, v_level, p_waktu, p_langkah);
      return v_skor;
    exception when unique_violation then
      update public.rehat_skor
         set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
       where game = p_game
         and lower(btrim(nama)) = lower(v_nama)
         and level = v_level
         and skor < v_skor;
      return v_skor;
    end;
  end if;

  if v_skor > v_lama then
    update public.rehat_skor
       set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
     where game = p_game
       and lower(btrim(nama)) = lower(v_nama)
       and level = v_level;
    return v_skor;
  end if;

  return v_lama;   -- skor lama masih lebih baik, tidak diubah
end;
$$;

-- hanya fungsi ini yang boleh dipanggil publik
revoke all on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text) from public;
grant execute on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text)
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. Pemeriksaan cepat setelah Run
-- ---------------------------------------------------------------------------
-- a) Kedua fungsi terpasang & security definer (harus dua baris bertanda "t"):
select p.proname, p.prosecdef as security_definer
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'public'
   and p.proname in ('rehat_kirim_skor','rehat_mulai_ronde');
--
-- b) Insert langsung harus GAGAL (hak tulis publik sudah dicabut):
--    insert into public.rehat_skor(game,nama,skor,level) values ('ngopi','Curang',99999,'');
--
-- c) Simulasi curang "mengaku 2 jam":
--    select public.rehat_mulai_ronde('ngopi','ujicurang0001');
--    select public.rehat_kirim_skor('ngopi','UjiCurang',93612,'',7200,null,'ujicurang0001');
--    -> hasilnya bukan 93612, melainkan sekitar 220 (plafon durasi server).
--
-- d) Anti replay masih berlaku (panggilan kedua nonce sama -> null):
--    select public.rehat_kirim_skor('ngopi','UjiCurang',50,'',30,null,'ujicurang0001');
