-- ============================================================================
--  rehat-reset-puzzle-v84.sql  —  RESET SKOR KHUSUS SUSUN (PUZZLE) SAJA
--
--  Jalankan SETELAH rehat-durasi-server-v83.sql. Aman diulang (idempotent).
--
--  Latar: SUSUN v84 menghapus tingkat 3x3/4x4/5x5 — sekarang selalu 16 potongan,
--  satu papan untuk semua. Karena itu:
--   1) Seluruh skor SUSUN lama (per tingkat) dihapus. FLYER & NGOPI TIDAK disentuh.
--   2) Buku nonce milik SUSUN ikut dibersihkan.
--   3) rehat_kirim_skor() diperbarui: level apa pun yang dikirim untuk puzzle
--      DIPAKSA '' (klien lama yang masih mengirim '4x4' tetap diterima, hanya
--      dicatat tanpa tingkat). Basis poin 6000, ambang minimal 10 langkah /
--      6 detik (bekas tingkat 4x4). Mode ketat & jangkar jam server dari v83
--      tetap berlaku.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Jaring pengaman: pastikan tabel ada (dilewati otomatis bila sudah ada)
-- ---------------------------------------------------------------------------
create table if not exists public.rehat_skor (
  id          bigint generated by default as identity primary key,
  game        text        not null,
  nama        text        not null,
  skor        integer     not null default 0,
  created_at  timestamptz not null default now()
);
alter table public.rehat_skor add column if not exists level   text not null default '';
alter table public.rehat_skor add column if not exists waktu   integer;
alter table public.rehat_skor add column if not exists langkah integer;

create table if not exists public.rehat_nonce (
  nonce      text primary key,
  game       text,
  nama       text,
  created_at timestamptz not null default now()
);
alter table public.rehat_nonce add column if not exists dipakai    boolean not null default true;
alter table public.rehat_nonce add column if not exists dipakai_at timestamptz;

-- ---------------------------------------------------------------------------
-- 1. RESET: kosongkan skor & nonce milik SUSUN saja
-- ---------------------------------------------------------------------------
delete from public.rehat_skor  where game = 'puzzle';
delete from public.rehat_nonce where game = 'puzzle';

-- ---------------------------------------------------------------------------
-- 2. PINTU MASUK SKOR (v84: SUSUN tanpa tingkat; selebihnya sama dengan v83)
-- ---------------------------------------------------------------------------
create or replace function public.rehat_kirim_skor(
  p_game    text,
  p_nama    text,
  p_skor    integer,
  p_level   text    default '',
  p_waktu   integer default null,
  p_langkah integer default null,
  p_nonce   text    default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nama   text;
  v_level  text;
  v_skor   integer;
  v_basis  integer;
  v_plafon integer;
  v_minlangkah integer;
  v_minwaktu   integer;
  v_lama   integer;
  v_banyak integer;
  v_mulai  timestamptz;
  v_dur    integer;
  v_waktu  integer;
  v_wajib_mulai boolean := true;   /* mode ketat: nonce wajib didaftarkan saat ronde mulai */
begin
  -- ---------- nama ----------
  v_nama := btrim(coalesce(p_nama, ''));
  if char_length(v_nama) < 1 or char_length(v_nama) > 24 then
    return null;
  end if;

  -- ---------- game ----------
  if p_game is null or p_game not in ('flyer','ngopi','puzzle') then
    return null;
  end if;

  -- ---------- level (v84: tingkat SUSUN dihapus) ----------
  -- Apa pun yang dikirim klien untuk puzzle (klien lama masih mengirim '4x4')
  -- dipaksa '' — satu papan untuk semua.
  v_level := '';

  -- ---------- durasi wajib & wajar ----------
  if p_waktu is null or p_waktu < 1 or p_waktu > 7200 then
    return null;
  end if;
  if p_langkah is not null and (p_langkah < 0 or p_langkah > 20000) then
    return null;
  end if;

  -- ---------- nonce wajib ----------
  if p_nonce is null or char_length(p_nonce) < 8 or char_length(p_nonce) > 64 then
    return null;
  end if;

  -- ---------- rem laju per nama (dihitung dari SAAT KIRIM) ----------
  select count(*) into v_banyak
    from public.rehat_nonce
   where nama = lower(v_nama)
     and coalesce(dipakai_at, created_at) > now() - interval '10 minutes';
  if v_banyak >= 30 then
    return null;
  end if;

  -- ---------- nonce sekali-pakai + jangkar jam server ----------
  update public.rehat_nonce
     set dipakai = true, nama = lower(v_nama), dipakai_at = now()
   where nonce = p_nonce
     and dipakai = false
   returning created_at into v_mulai;
  if not found then
    -- MODE KETAT: nonce yang tidak didaftarkan saat ronde mulai DITOLAK.
    -- Untuk masa transisi klien lama, set v_wajib_mulai := false.
    if v_wajib_mulai then
      return null;
    end if;
    begin
      insert into public.rehat_nonce(nonce, game, nama, dipakai, dipakai_at)
      values (p_nonce, p_game, lower(v_nama), true, now());
      v_mulai := null;
    exception when unique_violation then
      return null;   -- ronde ini sudah pernah dikirim (anti replay)
    end;
  end if;

  -- sapu bersih catatan nonce lama sesekali agar tabel tetap ringan
  if random() < 0.02 then
    delete from public.rehat_nonce where created_at < now() - interval '3 days';
  end if;

  -- durasi versi jam server (null bila mode transisi menerima klien lama)
  if v_mulai is not null then
    v_dur := greatest(1, floor(extract(epoch from (now() - v_mulai)))::int);
  else
    v_dur := null;
  end if;

  -- =========================================================================
  -- HITUNG ULANG / BATASI SKOR DI SERVER — angka dari klien tidak dipercaya
  -- =========================================================================
  if p_game = 'puzzle' then
    if p_langkah is null then return null; end if;

    -- v84: satu-satunya tingkat adalah 16 potongan (bekas 4x4)
    v_basis      := 6000;
    v_minlangkah := 10;   /* langkah berbobot: tukar*2 + putar */
    v_minwaktu   := 6;

    -- mustahil menyusun dengan langkah/waktu di bawah batas ini
    if p_langkah < v_minlangkah then return null; end if;
    if p_waktu   < v_minwaktu   then return null; end if;
    -- batas kecepatan ketukan manusia — tetap dari jam klien (jeda tak dihitung)
    if p_langkah > (p_waktu + 1) * 25 then return null; end if;

    -- waktu poin dijangkar jam server; jeda sampai 3 menit tetap dimaafkan
    if v_dur is not null then
      v_waktu := greatest(p_waktu, v_dur - 180);
    else
      v_waktu := p_waktu;
    end if;

    -- rumus resmi puzzle, dihitung di server (langkah berbobot: tukar*2+putar)
    v_skor := greatest(10, least(v_basis, v_basis - v_waktu * 30 - p_langkah * 4));

  else
    -- arcade: plafon laju terhadap durasi; durasi laporan klien dibatasi jam
    -- server (+15 dtk tenggang kirim). Yang dipakai selalu yang TERKECIL.
    --   flyer : 1 pipa butuh >= ~0,8 detik  -> plafon 1,3 poin/detik
    --   ngopi : item terbaik 5 poin per ~0,4 detik -> plafon 13 poin/detik
    if v_dur is not null then
      v_waktu := least(p_waktu, v_dur + 15);
    else
      v_waktu := p_waktu;
    end if;
    v_plafon := case p_game
                  when 'flyer' then 3  + ceil(v_waktu * 1.3)::int
                  else              12 + ceil(v_waktu * 13)::int
                end;
    v_skor := least(greatest(coalesce(p_skor, 0), 0), v_plafon);
  end if;

  if v_skor <= 0 or v_skor > 100000 then
    return null;
  end if;

  -- =========================================================================
  -- UPSERT: satu baris per (game, nama, level), hanya diganti bila lebih tinggi
  -- =========================================================================
  select skor into v_lama
    from public.rehat_skor
   where game = p_game
     and lower(btrim(nama)) = lower(v_nama)
     and level = v_level
   limit 1;

  if v_lama is null then
    begin
      insert into public.rehat_skor(game, nama, skor, level, waktu, langkah)
      values (p_game, v_nama, v_skor, v_level, p_waktu, p_langkah);
      return v_skor;
    exception when unique_violation then
      update public.rehat_skor
         set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
       where game = p_game
         and lower(btrim(nama)) = lower(v_nama)
         and level = v_level
         and skor < v_skor;
      return v_skor;
    end;
  end if;

  if v_skor > v_lama then
    update public.rehat_skor
       set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
     where game = p_game
       and lower(btrim(nama)) = lower(v_nama)
       and level = v_level;
    return v_skor;
  end if;

  return v_lama;   -- skor lama masih lebih baik, tidak diubah
end;
$$;

revoke all on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text) from public;
grant execute on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text)
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. Pemeriksaan cepat setelah Run
-- ---------------------------------------------------------------------------
-- a) SUSUN kosong, FLYER & NGOPI tidak tersentuh:
select game, count(*) as baris from public.rehat_skor group by game order by game;
--
-- b) Skor SUSUN baru diterima (level '' di server):
--    select public.rehat_mulai_ronde('puzzle','ujipuzzle0001');
--    select public.rehat_kirim_skor('puzzle','Uji',5000,'',40,24,'ujipuzzle0001');
--
-- c) Klien lama yang masih mengirim level '4x4' tetap diterima, dicatat '':
--    select public.rehat_mulai_ronde('puzzle','ujipuzzle0002');
--    select public.rehat_kirim_skor('puzzle','UjiLama',5000,'4x4',40,24,'ujipuzzle0002');
--    select game,nama,skor,level from public.rehat_skor where game='puzzle';
