-- ============================================================================
--  REHAT LEADERBOARD  v80  —  PENGAMANAN SKOR (anti input manual / curang)
--  Jalankan SEKALI di Supabase -> SQL Editor -> Run.
--  Aman dijalankan berulang (idempotent). Tidak menghapus data yang sudah ada.
--
--  Inti perubahan v79 -> v80:
--   1) Hak INSERT publik DICABUT. Sebelumnya policy "rehat_tulis_publik"
--      memakai (with check true), sehingga siapa pun yang melihat anon key di
--      kode game bisa mengirim skor palsu lewat curl/console.
--   2) Satu-satunya pintu masuk skor sekarang fungsi RPC rehat_kirim_skor()
--      yang bersifat SECURITY DEFINER dan memeriksa kewajaran ronde.
--   3) Skor PUZZLE dihitung ULANG di server dari (waktu, langkah, level).
--      Angka skor dari klien diabaikan sama sekali.
--   4) Skor FLYER/NGOPI dibatasi plafon laju maksimum permainan terhadap durasi.
--   5) Nonce sekali-pakai: satu ronde tidak bisa dikirim dua kali (anti replay),
--      plus rem laju maksimal 30 kiriman per nama / 10 menit.
--   6) Baca leaderboard tetap publik seperti biasa.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Pastikan tabel dasar & kolom ada (lanjutan v71..v79)
-- ---------------------------------------------------------------------------
create table if not exists public.rehat_skor (
  id          bigint generated by default as identity primary key,
  game        text        not null,
  nama        text        not null,
  skor        integer     not null default 0,
  created_at  timestamptz not null default now()
);

alter table public.rehat_skor add column if not exists level   text not null default '';
-- kolom bukti untuk audit / deteksi anomali
alter table public.rehat_skor add column if not exists waktu   integer;
alter table public.rehat_skor add column if not exists langkah integer;

create index if not exists rehat_skor_game_skor_idx
  on public.rehat_skor (game, skor desc);

create unique index if not exists rehat_skor_unik
  on public.rehat_skor (game, lower(btrim(nama)), level);

alter table public.rehat_skor enable row level security;

-- ---------------------------------------------------------------------------
-- 1. CABUT HAK TULIS PUBLIK  <-- ini inti pengamanannya
-- ---------------------------------------------------------------------------
drop policy if exists rehat_tulis_publik on public.rehat_skor;
drop policy if exists rehat_ubah_publik  on public.rehat_skor;
drop policy if exists rehat_hapus_publik on public.rehat_skor;

revoke insert, update, delete, truncate on public.rehat_skor from anon;
revoke insert, update, delete, truncate on public.rehat_skor from authenticated;

-- baca tetap terbuka supaya papan peringkat bisa tampil tanpa login
drop policy if exists rehat_baca_publik on public.rehat_skor;
create policy rehat_baca_publik on public.rehat_skor for select using (true);
grant select on public.rehat_skor to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. Buku nonce: satu ronde = satu kiriman (anti kirim ulang / replay)
-- ---------------------------------------------------------------------------
create table if not exists public.rehat_nonce (
  nonce      text primary key,
  game       text,
  nama       text,
  created_at timestamptz not null default now()
);
create index if not exists rehat_nonce_nama_idx
  on public.rehat_nonce (nama, created_at desc);

alter table public.rehat_nonce enable row level security;
-- tanpa policy apa pun: anon sama sekali tidak bisa membaca/menulis tabel ini.
revoke all on public.rehat_nonce from anon;
revoke all on public.rehat_nonce from authenticated;

-- ---------------------------------------------------------------------------
-- 3. SATU-SATUNYA PINTU MASUK SKOR
-- ---------------------------------------------------------------------------
create or replace function public.rehat_kirim_skor(
  p_game    text,
  p_nama    text,
  p_skor    integer,
  p_level   text    default '',
  p_waktu   integer default null,
  p_langkah integer default null,
  p_nonce   text    default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nama   text;
  v_level  text;
  v_skor   integer;
  v_basis  integer;
  v_plafon integer;
  v_minlangkah integer;
  v_minwaktu   integer;
  v_lama   integer;
  v_banyak integer;
begin
  -- ---------- nama ----------
  v_nama := btrim(coalesce(p_nama, ''));
  if char_length(v_nama) < 1 or char_length(v_nama) > 24 then
    return null;
  end if;

  -- ---------- game ----------
  if p_game is null or p_game not in ('flyer','ngopi','puzzle') then
    return null;
  end if;

  -- ---------- level ----------
  v_level := coalesce(p_level, '');
  if p_game = 'puzzle' then
    if v_level not in ('3x3','4x4','5x5') then return null; end if;
  else
    v_level := '';
  end if;

  -- ---------- durasi wajib & wajar ----------
  if p_waktu is null or p_waktu < 1 or p_waktu > 7200 then
    return null;
  end if;
  if p_langkah is not null and (p_langkah < 0 or p_langkah > 20000) then
    return null;
  end if;

  -- ---------- rem laju per nama ----------
  select count(*) into v_banyak
    from public.rehat_nonce
   where nama = lower(v_nama)
     and created_at > now() - interval '10 minutes';
  if v_banyak >= 30 then
    return null;
  end if;

  -- ---------- nonce sekali pakai ----------
  if p_nonce is null or char_length(p_nonce) < 8 or char_length(p_nonce) > 64 then
    return null;
  end if;
  begin
    insert into public.rehat_nonce(nonce, game, nama)
    values (p_nonce, p_game, lower(v_nama));
  exception when unique_violation then
    return null;   -- ronde ini sudah pernah dikirim
  end;

  -- sapu bersih catatan nonce lama sesekali agar tabel tetap ringan
  if random() < 0.02 then
    delete from public.rehat_nonce where created_at < now() - interval '3 days';
  end if;

  -- =========================================================================
  -- HITUNG ULANG / BATASI SKOR DI SERVER — angka dari klien tidak dipercaya
  -- =========================================================================
  if p_game = 'puzzle' then
    if p_langkah is null then return null; end if;

    v_basis      := case v_level when '3x3' then 3000 when '5x5' then 9500 else 6000 end;
    v_minlangkah := case v_level when '3x3' then 6    when '5x5' then 16   else 10   end;
    v_minwaktu   := case v_level when '3x3' then 3    when '5x5' then 12   else 6    end;

    -- mustahil menyusun dengan langkah/waktu di bawah batas ini
    if p_langkah < v_minlangkah then return null; end if;
    if p_waktu   < v_minwaktu   then return null; end if;
    -- batas kecepatan ketukan manusia
    if p_waktu < ceil(p_langkah * 0.35) then return null; end if;

    -- rumus resmi puzzle, dihitung di server
    v_skor := greatest(10, least(v_basis, v_basis - p_waktu * 30 - p_langkah * 8));

  else
    -- arcade: skor dibatasi laju maksimum yang mungkin dicapai dalam p_waktu detik
    --   flyer : 1 pipa butuh >= ~0,8 detik  -> plafon 1,3 poin/detik
    --   ngopi : item terbaik 5 poin per ~0,4 detik -> plafon 13 poin/detik
    v_plafon := case p_game
                  when 'flyer' then 3  + ceil(p_waktu * 1.3)::int
                  else              12 + ceil(p_waktu * 13)::int
                end;
    v_skor := least(greatest(coalesce(p_skor, 0), 0), v_plafon);
  end if;

  if v_skor <= 0 or v_skor > 100000 then
    return null;
  end if;

  -- =========================================================================
  -- UPSERT: satu baris per (game, nama, level), hanya diganti bila lebih tinggi
  -- =========================================================================
  select skor into v_lama
    from public.rehat_skor
   where game = p_game
     and lower(btrim(nama)) = lower(v_nama)
     and level = v_level
   limit 1;

  if v_lama is null then
    begin
      insert into public.rehat_skor(game, nama, skor, level, waktu, langkah)
      values (p_game, v_nama, v_skor, v_level, p_waktu, p_langkah);
      return v_skor;
    exception when unique_violation then
      update public.rehat_skor
         set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
       where game = p_game
         and lower(btrim(nama)) = lower(v_nama)
         and level = v_level
         and skor < v_skor;
      return v_skor;
    end;
  end if;

  if v_skor > v_lama then
    update public.rehat_skor
       set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
     where game = p_game
       and lower(btrim(nama)) = lower(v_nama)
       and level = v_level;
    return v_skor;
  end if;

  return v_lama;   -- skor lama masih lebih baik, tidak diubah
end;
$$;

-- hanya fungsi ini yang boleh dipanggil publik
revoke all on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text) from public;
grant execute on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text)
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 4. Pemeriksaan cepat setelah Run (opsional, hapus komentar untuk mencoba)
-- ---------------------------------------------------------------------------
-- Harus GAGAL / tidak tersimpan (insert langsung sudah dicabut):
--   insert into public.rehat_skor(game,nama,skor,level) values ('puzzle','Curang',99999,'4x4');
--
-- Harus DITOLAK (null) karena waktu/langkah mustahil:
--   select public.rehat_kirim_skor('puzzle','Uji',99999,'4x4',1,1,'ujitolak0001');
--
-- Harus DITERIMA dan skornya dihitung ulang server (bukan 99999):
--   select public.rehat_kirim_skor('puzzle','Uji',99999,'4x4',40,24,'ujiterima0001');
--
-- Kiriman kedua dengan nonce sama harus null (anti replay):
--   select public.rehat_kirim_skor('puzzle','Uji',5000,'4x4',40,24,'ujiterima0001');
--
--   select game,nama,skor,level,waktu,langkah from public.rehat_skor order by id desc limit 5;
