-- ============================================================================
--  rehat-tutup-lomba-v85.sql  —  TUTUP LOMBA OTOMATIS DI SISI SERVER
--
--  Jalankan SETELAH rehat-durasi-server-v83.sql dan rehat-reset-puzzle-v84.sql.
--  Aman diulang (create or replace / if not exists).
--
--  PENUTUPANNYA SEMENTARA — gim dibuka lagi untuk dimainkan santai setelah
--  acara selesai (sisi klien membuka lagi otomatis; bawaan: 21 Sep 2026 06:00
--  WITA, ubah konstanta BUKA_LAGI di berkas-berkas rehat/*.html).
--
--  Yang PERMANEN hanya pencatatan skor lomba: mulai 20 Sep 2026 22:00 WITA
--  (Asia/Makassar, UTC+8), JAM SERVER menolak:
--    - rehat_mulai_ronde()  -> ronde baru tidak bisa didaftarkan
--    - rehat_kirim_skor()   -> skor apa pun tidak lagi tercatat
--  Jadi papan rekor lomba membeku = hasil final yang sah untuk pengumuman
--  pemenang, selamanya. Papan tetap bisa dibaca publik.
--  Sisi klien juga menutup tampilannya sendiri; berkas inilah penjaga
--  sebenarnya, karena jam HP pemain bisa diakali, jam server tidak.
--
--  Ubah tanggalnya cukup di dua konstanta di bawah bila event bergeser.
--
--  ALTERNATIF (bila suatu hari papan mau dihidupkan lagi untuk musim baru):
--  ganti gerbang waktu di kedua fungsi menjadi cek jendela tutup saja:
--    if now() >= timestamp with time zone '2026-09-20 22:00:00+08'
--       and now() <  timestamp with time zone '2026-09-21 06:00:00+08' then ...
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 0. Jaring pengaman: tabel & kolom (dilewati otomatis bila sudah ada)
-- ---------------------------------------------------------------------------
create table if not exists public.rehat_skor (
  id          bigint generated by default as identity primary key,
  game        text        not null,
  nama        text        not null,
  skor        integer     not null default 0,
  created_at  timestamptz not null default now()
);
alter table public.rehat_skor add column if not exists level   text not null default '';
alter table public.rehat_skor add column if not exists waktu   integer;
alter table public.rehat_skor add column if not exists langkah integer;

create table if not exists public.rehat_nonce (
  nonce      text primary key,
  game       text,
  nama       text,
  created_at timestamptz not null default now()
);
alter table public.rehat_nonce add column if not exists dipakai    boolean not null default true;
alter table public.rehat_nonce add column if not exists dipakai_at timestamptz;

-- ---------------------------------------------------------------------------
-- 1. PENDAFTARAN JAM MULAI RONDE + gerbang tutup lomba
-- ---------------------------------------------------------------------------
create or replace function public.rehat_mulai_ronde(
  p_game  text,
  p_nonce text
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_baru integer;
begin
  -- ===== LOMBA SUDAH DITUTUP? (20 Sep 2026 22:00 WITA) =====
  if now() >= timestamp with time zone '2026-09-20 22:00:00+08' then
    return;
  end if;

  if p_game is null or p_game not in ('flyer','ngopi','puzzle') then return; end if;
  if p_nonce is null or char_length(p_nonce) < 8 or char_length(p_nonce) > 64 then return; end if;

  -- rem darurat anti banjir pendaftaran (jauh di atas pemakaian wajar acara)
  select count(*) into v_baru
    from public.rehat_nonce
   where created_at > now() - interval '1 hour';
  if v_baru > 50000 then return; end if;

  begin
    insert into public.rehat_nonce(nonce, game, nama, dipakai)
    values (p_nonce, p_game, '', false);
  exception when unique_violation then
    return;  -- nonce sudah terdaftar: abaikan saja
  end;

  -- sapu bersih catatan lama sesekali agar tabel tetap ringan
  if random() < 0.02 then
    delete from public.rehat_nonce where created_at < now() - interval '3 days';
  end if;
end;
$$;

revoke all on function public.rehat_mulai_ronde(text,text) from public;
grant execute on function public.rehat_mulai_ronde(text,text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. PINTU MASUK SKOR + gerbang tutup lomba (selebihnya identik dengan v84)
-- ---------------------------------------------------------------------------
create or replace function public.rehat_kirim_skor(
  p_game    text,
  p_nama    text,
  p_skor    integer,
  p_level   text    default '',
  p_waktu   integer default null,
  p_langkah integer default null,
  p_nonce   text    default null
) returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_nama   text;
  v_level  text;
  v_skor   integer;
  v_basis  integer;
  v_plafon integer;
  v_minlangkah integer;
  v_minwaktu   integer;
  v_lama   integer;
  v_banyak integer;
  v_mulai  timestamptz;
  v_dur    integer;
  v_waktu  integer;
  v_wajib_mulai boolean := true;   /* mode ketat: nonce wajib didaftarkan saat ronde mulai */
begin
  -- ===== LOMBA SUDAH DITUTUP? (20 Sep 2026 22:00 WITA) — jam server =====
  if now() >= timestamp with time zone '2026-09-20 22:00:00+08' then
    return null;
  end if;

  -- ---------- nama ----------
  v_nama := btrim(coalesce(p_nama, ''));
  if char_length(v_nama) < 1 or char_length(v_nama) > 24 then
    return null;
  end if;

  -- ---------- game ----------
  if p_game is null or p_game not in ('flyer','ngopi','puzzle') then
    return null;
  end if;

  -- ---------- level (v84: tingkat SUSUN dihapus — satu papan untuk semua) ----------
  v_level := '';

  -- ---------- durasi wajib & wajar ----------
  if p_waktu is null or p_waktu < 1 or p_waktu > 7200 then
    return null;
  end if;
  if p_langkah is not null and (p_langkah < 0 or p_langkah > 20000) then
    return null;
  end if;

  -- ---------- nonce wajib ----------
  if p_nonce is null or char_length(p_nonce) < 8 or char_length(p_nonce) > 64 then
    return null;
  end if;

  -- ---------- rem laju per nama (dihitung dari SAAT KIRIM) ----------
  select count(*) into v_banyak
    from public.rehat_nonce
   where nama = lower(v_nama)
     and coalesce(dipakai_at, created_at) > now() - interval '10 minutes';
  if v_banyak >= 30 then
    return null;
  end if;

  -- ---------- nonce sekali-pakai + jangkar jam server ----------
  update public.rehat_nonce
     set dipakai = true, nama = lower(v_nama), dipakai_at = now()
   where nonce = p_nonce
     and dipakai = false
   returning created_at into v_mulai;
  if not found then
    -- MODE KETAT: nonce yang tidak didaftarkan saat ronde mulai DITOLAK.
    if v_wajib_mulai then
      return null;
    end if;
    begin
      insert into public.rehat_nonce(nonce, game, nama, dipakai, dipakai_at)
      values (p_nonce, p_game, lower(v_nama), true, now());
      v_mulai := null;
    exception when unique_violation then
      return null;   -- ronde ini sudah pernah dikirim (anti replay)
    end;
  end if;

  -- sapu bersih catatan nonce lama sesekali agar tabel tetap ringan
  if random() < 0.02 then
    delete from public.rehat_nonce where created_at < now() - interval '3 days';
  end if;

  -- durasi versi jam server
  if v_mulai is not null then
    v_dur := greatest(1, floor(extract(epoch from (now() - v_mulai)))::int);
  else
    v_dur := null;
  end if;

  -- =========================================================================
  -- HITUNG ULANG / BATASI SKOR DI SERVER — angka dari klien tidak dipercaya
  -- =========================================================================
  if p_game = 'puzzle' then
    if p_langkah is null then return null; end if;

    -- v84: satu-satunya tingkat adalah 16 potongan (bekas 4x4)
    v_basis      := 6000;
    v_minlangkah := 10;   /* langkah berbobot: tukar*2 + putar */
    v_minwaktu   := 6;

    if p_langkah < v_minlangkah then return null; end if;
    if p_waktu   < v_minwaktu   then return null; end if;
    -- batas kecepatan ketukan manusia — tetap dari jam klien (jeda tak dihitung)
    if p_langkah > (p_waktu + 1) * 25 then return null; end if;

    -- waktu poin dijangkar jam server; jeda sampai 3 menit tetap dimaafkan
    if v_dur is not null then
      v_waktu := greatest(p_waktu, v_dur - 180);
    else
      v_waktu := p_waktu;
    end if;

    -- rumus resmi puzzle, dihitung di server (langkah berbobot: tukar*2+putar)
    v_skor := greatest(10, least(v_basis, v_basis - v_waktu * 30 - p_langkah * 4));

  else
    -- arcade: plafon laju terhadap durasi; durasi laporan klien dibatasi jam
    -- server (+15 dtk tenggang kirim). Yang dipakai selalu yang TERKECIL.
    --   flyer : 1 pipa butuh >= ~0,8 detik  -> plafon 1,3 poin/detik
    --   ngopi : item terbaik 5 poin per ~0,4 detik -> plafon 13 poin/detik
    if v_dur is not null then
      v_waktu := least(p_waktu, v_dur + 15);
    else
      v_waktu := p_waktu;
    end if;
    v_plafon := case p_game
                  when 'flyer' then 3  + ceil(v_waktu * 1.3)::int
                  else              12 + ceil(v_waktu * 13)::int
                end;
    v_skor := least(greatest(coalesce(p_skor, 0), 0), v_plafon);
  end if;

  if v_skor <= 0 or v_skor > 100000 then
    return null;
  end if;

  -- =========================================================================
  -- UPSERT: satu baris per (game, nama, level), hanya diganti bila lebih tinggi
  -- =========================================================================
  select skor into v_lama
    from public.rehat_skor
   where game = p_game
     and lower(btrim(nama)) = lower(v_nama)
     and level = v_level
   limit 1;

  if v_lama is null then
    begin
      insert into public.rehat_skor(game, nama, skor, level, waktu, langkah)
      values (p_game, v_nama, v_skor, v_level, p_waktu, p_langkah);
      return v_skor;
    exception when unique_violation then
      update public.rehat_skor
         set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
       where game = p_game
         and lower(btrim(nama)) = lower(v_nama)
         and level = v_level
         and skor < v_skor;
      return v_skor;
    end;
  end if;

  if v_skor > v_lama then
    update public.rehat_skor
       set skor = v_skor, created_at = now(), waktu = p_waktu, langkah = p_langkah
     where game = p_game
       and lower(btrim(nama)) = lower(v_nama)
       and level = v_level;
    return v_skor;
  end if;

  return v_lama;   -- skor lama masih lebih baik, tidak diubah
end;
$$;

revoke all on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text) from public;
grant execute on function public.rehat_kirim_skor(text,text,integer,text,integer,integer,text)
  to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. Pemeriksaan cepat setelah Run
-- ---------------------------------------------------------------------------
-- a) Kedua fungsi memuat gerbang waktu (harus dua baris "t"):
select p.proname, p.prosecdef as security_definer
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
 where n.nspname = 'public'
   and p.proname in ('rehat_kirim_skor','rehat_mulai_ronde');
--
-- b) SELAMA lomba masih berjalan, kiriman normal tetap diterima:
--    select public.rehat_mulai_ronde('ngopi','ujilomba0001');
--    select public.rehat_kirim_skor('ngopi','Uji',500,'',45,null,'ujilomba0001');
--
-- c) SETELAH 20 Sep 2026 22:00 WITA, panggilan yang sama harus menghasilkan
--    null (tidak tercatat) — itulah gerbang penutupnya.
